### PR TITLE
[FIXED] Dropdown Menu in Mobile View After Navigation 

### PR DESCRIPTION
**Pull request by PrayanshParmar**
Fixes:
Issue  (#12)

Tasks Completed
- [x]  Implement functionality to close the dropdown menu after a navigation option is clicked:
- [ ]  Add an event listener to the dropdown options to detect clicks. (No need to write custome listener, shadcnUI take care of event handling)
- [x]  Ensure that the dropdown menu closes after the page navigation is initiated.
- [x]  Test the implementation:
- [x]  Verify that the dropdown closes on all mobile devices and orientations.
- [x]  Check that the navigation works correctly after closing the dropdown.

Sample Video

https://github.com/user-attachments/assets/474f775c-74fe-4243-8db0-923089a422f1

### CODE REVIEW

**Comment by A91y** [comment]
@mayank-dev07 the hover effect seems to be white bg. Please check it out.

**Comment by PrayanshParmar** [comment]
I have not changed hover colour it is same as it was before.

**Comment by PrayanshParmar** [comment]
Below is the previous dropdown which is not responsive, neither any howering effect nore in proper alignment, I have fixed it and given it a proper howering and alignment. 

https://github.com/user-attachments/assets/e2ae94bd-f36f-4a94-adb0-35e12558b9ea

**Comment by A91y** [comment]
@mayank-dev07 please review this

**Review by mayank-dev07 — COMMENTED** [review]
@A91y looks good to me.

**Pull request merged**
