### PR TITLE
Removed Comments an unused imports

### PR DESCRIPTION
**Pull request by Zaid-B24**
Made the necessary changes by removing unused code, also removed commented codes and unused imports

### CODE REVIEW

**Comment by Zaid-B24** [comment]
@A91y issue no 2, about removing unused code.
I have made the necessary changes and created a new pull request

**Review by A91y — CHANGES_REQUESTED** [review]
Do not update sitemap file and don't upload sitemap-0.xml

**Comment by Zaid-B24** [comment]
@A91y I made the necessary changes, can u merge the PR.

**Comment by A91y** [comment]
@Zaid-B24 don't modify .gitignore and sitemap.xml

**Comment by Zaid-B24** [comment]
@A91y made the changes.

**Comment by A91y** [comment]
@Zaid-B24 use of such non-descriptive commit message is not allowed. And when you make a PR that fixes some issue, you need to link the issue to the PR.

**Comment by Zaid-B24** [comment]
@A91y My bad, I restored .gitignore file to original state, also removed sitemap-0.xml from being upload. I removed the unused code and imports and commented code, this PR is in reference to issue no. #2

**Review by A91y — COMMENTED** [review]
lgtm

**Comment by A91y** [comment]
Thanks @Zaid-B24

**Comment by Zaid-B24** [comment]
thank you @A91y

**Pull request merged**
