### PR TITLE
[Enhancement] Improve Profile Page Load Time on Revisit

### PR DESCRIPTION
**Pull request by atj393**
- Added caching mechanism to store radar data in localStorage.
- Display cached radar data immediately on profile page revisit.
- Fetch latest radar data in the background and update once available.
- Improved user experience by reducing loading times for repeat visitors.
- Aligned with issue #17 to enhance page responsiveness and interactivity.

### CODE REVIEW

**Comment by atj393** [comment]
@A91y Can you review it and update me? 
Also, can you add the labels, please?

**Review by mayank-dev07 — CHANGES_REQUESTED** [review]
@atj393 thanks for improving profile page load time. Please update the changes that the accordion component should also not load on revisit and also give a button to refresh on clicking that button load the accordion component.

**Comment by atj393** [comment]
@mayank-dev07 I think we should consider it as a new issue as it is navigating in a different direction than the initial #17.
Can you create a new issue ticket with the new requirements and assign it to me? Thanks.

**Comment by atj393** [comment]
@A91y I think you are asking @mayank-dev07.

**Comment by A91y** [comment]
> @A91y I think you are asking @mayank-dev07.

@atj393 I'm asking you, why do you need to create a separate issue as optimizing the complete page on revisit is defined in issue?

**Comment by A91y** [comment]
thanks @atj393

**Comment by atj393** [comment]
@A91y Thank you!

**Pull request merged**
