### PR TITLE
[Security Fix] Removed sensitive information from console logs in production

### LINKED ISSUE #4: [Security] Sensitive Information Logged in Console in Production
### **Description**
Sensitive information, such as user details (e.g., names, emails, and session details), is currently being logged to the browser console in the production environment. This can pose a security and privacy risk, especially if someone gains access to these logs or if the data is inadvertently exposed.

### **Details**
- **Affected Data:**
  - User profile information (e.g., name, email, location, and other sensitive fields).
  - Session details such as `sessionUser` objects, including GitHub profile information.

### **Steps to Reproduce**
1. Navigate to the live application in a browser.
2. Open the browser's Developer Tools (`F12` or `Ctrl + Shift + I`).
3. Go to the **Console** tab.
4. Log in as a user, and go to the profile page or dashboard.
5. Observe logs containing sensitive data in the console.

### **Expected Behavior**
- No sensitive information (e.g., user emails, names, etc.) should be logged in the console, especially in a production environment.

### **Suggested Fix**
- Remove or sanitize console logs to prevent sensitive data from being exposed.
- Ensure that logging is minimized or completely disabled in production builds.
- Use environment checks (e.g., `process.env.NODE_ENV`) to conditionally log messages only in development mode.

### **Impact**
This issue affects user privacy and can expose sensitive information, which is a potential risk for users of the platform.

### PR DESCRIPTION
**Pull request by atj393**
Fixes #4: Removed console logs containing sensitive information. Updated all `console.log` statements.

### CODE REVIEW

**Comment by A91y** [comment]
Instead of commenting, can you just remove them.

**Review by A91y — CHANGES_REQUESTED** [review]
Instead of commenting, can you just remove them.

**Comment by atj393** [comment]
@A91y I made a new commit: I removed logs and a few unnecessary codes from the Header component.

**Comment by A91y** [comment]
Lgtm.

**Review by A91y — COMMENTED** [review]
Lgtm

**Comment by A91y** [comment]
Thank you @atj393 for your contribution to Octasol!

**Comment by atj393** [comment]
@A91y  It was great working with you!

I like the project and the concept. If you can create some issues outlining current bugs, enhancements, or features, I would be interested in taking a look. Thanks!

**Comment by A91y** [comment]
> @A91y  It was great working with you!
> 
> I like the project and the concept. If you can create some issues outlining current bugs, enhancements, or features, I would be interested in taking a look. Thanks!

You can join the Octasol Discord to stay updated with the issues. (link in readme)

**Comment by atj393** [comment]
@A91y Thanks!

**Pull request merged**
